# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=26.1-1.1
group=com.ofekn.quick
java_version=25
run_minecraft_version=26.1.2

# Common
minecraft_version=26.1
mod_name=Quick
mod_author=OfekN
mod_id=quick
license=GNU GENERAL PUBLIC LICENSE
credits=
description=Quick item actions
minecraft_version_range=[26.1, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
# compile against 26.1
neo_form_version=26.1-1

# Fabric, see https://fabricmc.net/develop/ for new versions
# run against 26.1.2
fabric_version=0.149.0+26.1.2
fabric_loader_version=0.18.6

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
# run against 26.1.2
neoforge_version=26.1.2.65-beta
neoforge_loader_version_range=[4,)

# Integrations
curios_version=15.0.0-beta.2+26.1.2
refined_storage_neoforge_version=s5EsahvO
refined_storage_fabric_version=hksBRVwn
ae2_neoforge_version=vzrkvq3t
guideme_neoforge_version=wiNQW8T5
ae2_fabric_version=
simple_magnets_neoforge_version=
simple_magnets_fabric_version=

# Runtime toggles
run_with_curios=true
run_with_refined_storage=true
run_with_ae2=true
run_with_simple_magnets=true

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
