plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.3'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.5.3'
    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"

    if (refined_storage_fabric_version) {
        compileOnly "maven.modrinth:refined-storage:${refined_storage_fabric_version}"
    }
    if (ae2_neoforge_version) {
        compileOnly "maven.modrinth:ae2:${ae2_neoforge_version}"
    }
    if (simple_magnets_fabric_version) {
        compileOnly "maven.modrinth:simple-magnets:${simple_magnets_fabric_version}"
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

tasks.register('apiJar', Jar) {
    archiveClassifier = 'api'
    from(sourceSets.main.output) {
        include 'com/ofekn/quick/api/**'
    }
}

tasks.register('apiSourcesJar', Jar) {
    archiveClassifier = 'api-sources'
    from(sourceSets.main.allJava) {
        include 'com/ofekn/quick/api/**'
    }
}

jar.dependsOn(apiJar, apiSourcesJar)

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}
